"""Local static server and JSON API; no third-party dependencies."""

from __future__ import annotations

import json
import logging
import os
import re
import secrets
import threading
import uuid
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from urllib.parse import unquote, urlsplit

from agent import Agent, Memory, PLATFORMS, SUPPLIER_PROFILE_VERSION, TOOL_META, TOOL_SCHEMAS
from product_knowledge import catalog_payload
from llm_adapter import OpenAICompatiblePlanner, read_saved_config, write_saved_config


ROOT = Path(__file__).parent
MEMORY = Memory(ROOT / "data/agent.sqlite3")
LLM_CONFIG_PATH = ROOT / "data/llm_config.json"
SAVED_LLM_CONFIG = read_saved_config(LLM_CONFIG_PATH)
PLANNER = OpenAICompatiblePlanner(
    SAVED_LLM_CONFIG.get("url", os.getenv("PRINTOPS_LLM_URL", "")),
    SAVED_LLM_CONFIG.get("key", os.getenv("PRINTOPS_LLM_KEY", "")),
    SAVED_LLM_CONFIG.get("model", os.getenv("PRINTOPS_LLM_MODEL", "")),
)
LLM_LOCK = threading.Lock()
SESSION_LOCKS: dict[str, threading.Lock] = {}
SESSION_LOCKS_GUARD = threading.Lock()
MAX_BODY_BYTES = 1 * 1024 * 1024
SESSION_ID_PATTERN = re.compile(r"^[A-Za-z0-9_-]{1,64}$")
LOGGER = logging.getLogger("printops.server")
DEFAULT_PORT = 4174
PORT = int(os.getenv("PRINTOPS_PORT", str(DEFAULT_PORT)))

# Local access token: generated per process, injected into the served page,
# and required on every API call except /api/health. A random website cannot
# read it (same-origin policy), so browser-borne CSRF/DNS-rebinding requests
# fail with 401/403.
TOKEN_HEADER = "X-PrintOps-Token"
ACCESS_TOKEN = secrets.token_urlsafe(24)
# Static routes are whitelisted: the server must never expose source files,
# docs, .git or runtime data. Non-API paths outside this set return 404.
STATIC_FILES = {
    "": "index.html", "/": "index.html", "/index.html": "index.html",
    "/app.js": "app.js", "/styles.css": "styles.css",
}
STATIC_CONTENT_TYPES = {
    "index.html": "text/html; charset=utf-8",
    "app.js": "text/javascript; charset=utf-8",
    "styles.css": "text/css; charset=utf-8",
}
KEY_STORAGE_WARNING = ("API Key 以明文保存在本机 data/llm_config.json（文件权限 600）。"
                       "请勿把该文件提交到 Git 或分享给他人；更安全的做法是仅用环境变量提供 Key。")


class RequestError(Exception):
    """An expected client/API error that can be safely shown to the UI."""

    def __init__(self, message: str, status: int = 400, code: str = "BAD_REQUEST") -> None:
        super().__init__(message)
        self.message = message
        self.status = status
        self.code = code


def _key_storage_warning() -> str:
    """Warn when a plaintext API key is actually stored in the local config file."""
    try:
        return KEY_STORAGE_WARNING if read_saved_config(LLM_CONFIG_PATH).get("key") else ""
    except OSError:
        return ""


def llm_settings() -> dict[str, object]:
    with LLM_LOCK:
        payload: dict[str, object] = {"llm": PLANNER.public_config()}
    warning = _key_storage_warning()
    if warning:
        payload["keyStorageWarning"] = warning
    return payload


def update_llm_settings(body: dict[str, object]) -> dict[str, object]:
    url = str(body.get("url", "")).strip()
    model = str(body.get("model", "")).strip()
    clear = bool(body.get("clear"))
    if bool(url) != bool(model):
        raise ValueError("URL 和模型名需要同时填写，或同时留空使用规则模式")
    with LLM_LOCK:
        if clear or not url:
            PLANNER.configure("", "", "")
            write_saved_config(LLM_CONFIG_PATH, {"url": "", "model": "", "key": ""})
        else:
            api_key = str(body.get("key", "")).strip() or PLANNER.api_key
            PLANNER.configure(url, model, api_key)
            write_saved_config(LLM_CONFIG_PATH, {"url": PLANNER.base_url, "model": PLANNER.model, "key": PLANNER.api_key})
        payload: dict[str, object] = {"llm": PLANNER.public_config()}
    warning = _key_storage_warning()
    if warning:
        payload["keyStorageWarning"] = warning
    return payload


def _session_id(value: object) -> str | None:
    """Accept only opaque, bounded IDs generated by this app."""
    if value in (None, ""):
        return None
    if not isinstance(value, str) or not SESSION_ID_PATTERN.fullmatch(value):
        raise RequestError("会话标识无效，请刷新页面后重试", code="INVALID_SESSION")
    return value


def _session_lock(session_id: str) -> threading.Lock:
    with SESSION_LOCKS_GUARD:
        return SESSION_LOCKS.setdefault(session_id, threading.Lock())


def _item_index(body: dict[str, object]) -> int | None:
    value = body.get("itemIndex")
    return int(value) if value is not None else None


def dispatch_post(path: str, body: dict[str, object], agent: Agent):
    """Dispatch a parsed API payload without doing network I/O."""
    routes = {
        "/api/session": lambda: agent.snapshot(),
        "/api/chat": lambda: agent.chat(str(body.get("text", "")), body.get("patch"), _item_index(body)),
        "/api/choose": lambda: agent.choose(str(body.get("optionId", "")), _item_index(body)),
        "/api/generate": lambda: agent.generate(),
        "/api/confirm": lambda: agent.confirm(str(body.get("note", ""))),
        "/api/quote/status": lambda: agent.quote_status(str(body.get("requestId", "")).strip() or None),
        "/api/quote/cancel": lambda: agent.cancel_quote(
            str(body.get("requestId", "")).strip() or None,
            str(body.get("reason", "用户取消询价")),
        ),
        "/api/preflight": lambda: agent.upload(
            str(body.get("fileName", "")), int(body.get("sizeBytes", 0)),
            int(body["pageCount"]) if body.get("pageCount") is not None else None,
            body.get("encrypted") is True, body.get("readable") is not False,
            body.get("inspection"), body.get("expectedSize"), _item_index(body)),
        "/api/platform": lambda: agent.set_platform(str(body.get("platformId", "generic"))),
        "/api/tools/call": lambda: agent.call_tool(str(body.get("toolName", "")), body.get("payload", {})),
    }
    action = routes.get(path)
    if action is None:
        raise RequestError("接口不存在", 404, "NOT_FOUND")
    return action()


def dispatch_get(path: str) -> dict[str, object] | None:
    """Return public GET payloads; ``None`` delegates to static file handling."""
    if path == "/api/health":
        return {"ok": True}
    if path == "/api/settings":
        return llm_settings()
    if path == "/api/platforms":
        return {"platforms": [{"id": key, **value, "supplierProfileVersion": SUPPLIER_PROFILE_VERSION}
                               for key, value in PLATFORMS.items()]}
    if path == "/api/tools":
        tools = [{**dict(meta), **dict(TOOL_SCHEMAS.get(name, {}))} for name, meta in TOOL_META.items()]
        return {"tools": tools}
    if path == "/api/products":
        return catalog_payload()
    return None


class Handler(BaseHTTPRequestHandler):
    def _origin_allowed(self) -> bool:
        """Same-origin check: a present Origin header must match Host."""
        origin = self.headers.get("Origin")
        if not origin:
            return True
        try:
            return urlsplit(origin).netloc == (self.headers.get("Host") or "")
        except ValueError:
            return False

    def _authorized(self) -> bool:
        token = self.headers.get(TOKEN_HEADER, "")
        try:
            return secrets.compare_digest(token.encode("utf-8"), ACCESS_TOKEN.encode("utf-8"))
        except (TypeError, ValueError, UnicodeEncodeError):
            return False

    def _discard_body(self) -> None:
        """Read and drop a pending request body.

        Closing a connection with unread body data makes Windows emit a RST
        that can abort an unrelated later connection accepted from the same
        backlog, so every early rejection drains the declared body first.
        """
        raw_length = self.headers.get("Content-Length")
        try:
            remaining = int(raw_length) if raw_length else 0
        except (TypeError, ValueError):
            return
        if remaining <= 0:
            return
        try:
            self._drain(remaining)
        except (BrokenPipeError, ConnectionResetError, OSError):
            pass

    def _guard(self) -> bool:
        """Reject cross-origin and tokenless API access with a JSON error."""
        if not self._origin_allowed():
            self._discard_body()
            self.error_response(RequestError("跨来源请求被拒绝", 403, "FORBIDDEN_ORIGIN"))
            return False
        if not self._authorized():
            self._discard_body()
            self.error_response(RequestError("本地访问令牌缺失或不匹配，请刷新页面后重试", 401, "UNAUTHORIZED"))
            return False
        return True

    def do_GET(self):
        self.request_id = uuid.uuid4().hex[:12]
        path = unquote(urlsplit(self.path).path)
        try:
            if path.startswith("/api/"):
                if path != "/api/health" and not self._guard():
                    return None
                public_payload = dispatch_get(path)
                if public_payload is not None:
                    return self.reply(public_payload)
                return self.error_response(RequestError("接口不存在", 404, "NOT_FOUND"))
            return self.serve_static(path)
        except RequestError as error:
            return self.error_response(error)
        except (BrokenPipeError, ConnectionResetError):
            return None
        except Exception:
            LOGGER.exception("GET request failed requestId=%s path=%s", self.request_id, path)
            return self.error_response(RequestError("服务暂时无法处理请求，请重试", 500, "INTERNAL_ERROR"))

    def do_POST(self):
        self.request_id = uuid.uuid4().hex[:12]
        path = unquote(urlsplit(self.path).path)
        try:
            if not self._guard():
                return None
            body = self.read_json()
            if path == "/api/settings":
                try:
                    return self.reply(update_llm_settings(body))
                except ValueError as error:
                    raise RequestError(str(error), 400, "INVALID_SETTINGS")
            if path == "/api/model/test":
                with LLM_LOCK:
                    has_override = any(key in body for key in ("url", "model", "key"))
                    tester = PLANNER
                    if has_override:
                        tester = OpenAICompatiblePlanner(timeout=PLANNER.timeout)
                        try:
                            test_url = str(body.get("url", "")).strip()
                            test_model = str(body.get("model", "")).strip()
                            test_key = str(body.get("key", "")).strip()
                            if not test_key and test_url == PLANNER.base_url and test_model == PLANNER.model:
                                test_key = PLANNER.api_key
                            tester.configure(test_url, test_model, test_key)
                        except ValueError as error:
                            raise RequestError(str(error), 400, "INVALID_SETTINGS")
                    result = tester.test_connection()
                    return self.reply({"llm": tester.public_config(), "test": result})
            session_id = _session_id(body.get("sessionId"))
            if session_id:
                # Lock before loading state so concurrent requests cannot read
                # the same snapshot and overwrite each other's changes.
                with _session_lock(session_id):
                    return self.reply(dispatch_post(path, body, Agent(MEMORY, session_id, planner=PLANNER)))
            agent = Agent(MEMORY, planner=PLANNER)
            with _session_lock(agent.id):
                return self.reply(dispatch_post(path, body, agent))
        except RequestError as error:
            return self.error_response(error)
        except (TypeError, ValueError):
            return self.error_response(RequestError("请求参数格式不正确", 400, "INVALID_PAYLOAD"))
        except (BrokenPipeError, ConnectionResetError):
            return None
        except Exception:
            LOGGER.exception("POST request failed requestId=%s path=%s", self.request_id, path)
            return self.error_response(RequestError("本次处理失败，请重试", 500, "AGENT_ERROR"))

    def read_json(self) -> dict[str, object]:
        content_length = self.headers.get("Content-Length")
        if content_length is None:
            raise RequestError("请求缺少内容长度", 411, "LENGTH_REQUIRED")
        try:
            length = int(content_length)
        except (TypeError, ValueError):
            raise RequestError("请求内容长度无效", 400, "INVALID_LENGTH")
        if length < 0:
            raise RequestError("请求内容长度无效", 400, "INVALID_LENGTH")
        if length > MAX_BODY_BYTES:
            # Drain the declared body first so the client can finish writing
            # and actually receive the 413 instead of a connection reset.
            self._drain(length)
            raise RequestError("请求内容过大，请缩小后重试", 413, "PAYLOAD_TOO_LARGE")
        raw = self.rfile.read(length)
        if not raw:
            return {}
        content_type = (self.headers.get("Content-Type") or "").split(";", 1)[0].strip().lower()
        if content_type and content_type != "application/json":
            raise RequestError("请求必须使用 JSON 格式", 415, "UNSUPPORTED_MEDIA_TYPE")
        try:
            value = json.loads(raw)
        except (TypeError, ValueError, json.JSONDecodeError):
            raise RequestError("请求 JSON 无法解析", 400, "INVALID_JSON")
        if not isinstance(value, dict):
            raise RequestError("请求体必须是 JSON 对象", 400, "INVALID_PAYLOAD")
        return value

    def _drain(self, length: int, cap: int = 16 * 1024 * 1024) -> None:
        remaining = min(length, cap)
        while remaining > 0:
            chunk = self.rfile.read(min(remaining, 65536))
            if not chunk:
                break
            remaining -= len(chunk)

    def serve_static(self, path: str):
        """Serve only whitelisted static files; the page carries the access token."""
        name = STATIC_FILES.get(path)
        if name is None:
            return self.error_response(RequestError("资源不存在", 404, "NOT_FOUND"))
        try:
            raw = (ROOT / name).read_bytes()
        except OSError:
            return self.error_response(RequestError("资源不存在", 404, "NOT_FOUND"))
        if name == "index.html":
            raw = index_html_with_token(raw)
        self.send_response(200)
        self.send_header("Content-Type", STATIC_CONTENT_TYPES[name])
        self.send_header("Content-Length", str(len(raw)))
        self.send_header("Cache-Control", "no-store")
        self.send_header("X-Request-ID", getattr(self, "request_id", ""))
        self.end_headers()
        try:
            self.wfile.write(raw)
        except (BrokenPipeError, ConnectionResetError):
            return None

    def reply(self, data, status=200):
        raw = json.dumps(data, ensure_ascii=False).encode()
        self.send_response(status)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(raw)))
        self.send_header("X-Request-ID", getattr(self, "request_id", ""))
        self.end_headers()
        try:
            self.wfile.write(raw)
        except (BrokenPipeError, ConnectionResetError):
            return None

    def error_response(self, error: RequestError):
        return self.reply({"ok": False, "code": error.code, "message": error.message,
                           "requestId": getattr(self, "request_id", "")}, error.status)

    def log_message(self, format, *args):
        # Log only the normalized path; request query strings can contain secrets.
        LOGGER.info("%s %s", self.command, unquote(urlsplit(self.path).path))


def index_html_with_token(raw: bytes) -> bytes:
    """Inject the per-process access token into the served page."""
    html = raw.decode("utf-8")
    script = f"<script>window.__PRINTOPS_TOKEN__={json.dumps(ACCESS_TOKEN)};</script>"
    if "</head>" in html:
        html = html.replace("</head>", f"{script}</head>", 1)
    else:
        html = script + html
    return html.encode("utf-8")


if __name__ == "__main__":
    print(f"PrintOps order agent: http://localhost:{PORT}")
    print(f"本地访问令牌（curl 调试用 -H 'X-PrintOps-Token: ...'）：{ACCESS_TOKEN}")
    ThreadingHTTPServer(("127.0.0.1", PORT), Handler).serve_forever()
